version: "2"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: app.dev
    volumes:
      - .:/go/src/go-mysql-rest-api
    working_dir: /go/src/go-mysql-rest-api
    command: go run main.go
    ports:
      - "3000:3000" 
    links:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: mariadb:10.2
    container_name: database.dev
    hostname: database.dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pasaribu
      MYSQL_DATABASE: shopee
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/my.cnf