# Telling to use Docker's golang ready image
FROM golang:1.20

EXPOSE 8080

RUN apt-get update && apt-get install -y default-mysql-client
# ADD . /home

# WORKDIR /home

# RUN \
#         apk add --no-cache bash git openssh && \
#         go get -u github.com/minio/minio-go
        

# CMD [ "go", "run", "main.go" ]

